## Crash Data Wrangling Jupyter Notebook

**Author:** Eric Englin 

**Date:** 4/1/22

**Purpose:** This notebook will combine IMARS datasets over three time periods and change data to merge with CDS and STARS datasets

In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import os
from shapely.geometry import Point, LineString, Polygon

In [2]:
myworkingdirectory = r"C:\Users\Eric.Englin\OneDrive - DOT OST\TSP"
os.chdir(myworkingdirectory)

## Step 1: Concatenate Similar Datasets 

**Note:** Datasets have been divided across three time periods, so these must be combined to start joining the tables together.

In [3]:
path = './data/IMARS'

files = os.listdir(path)

for f in files:
    print(f)

NPS GOccIvPA Command Address 2011-2015.xlsx
NPS GOccIvPA Command Address 2016 to 4-2018.xlsx
NPS GOccIvPA Command Address 4-2018 to 6-2021.xlsx
NPS MVCOccGPersonReport Command 2011 to 2015.xlsx
NPS MVCOccGPersonReport Command 2016 to 4-2018.xlsx
NPS MVCOccGPersonReport Command 4-2018 to 6-2021.xlsx
NPS MVCOccReportCommand_Classification 2011-2015.xlsx
NPS MVCOccReportCommand_Classification 2016 to 4-2018.xlsx
NPS MVCOccReportCommand_Classification 4-2018 to 6-2021.xlsx
NPS MVCOccVehicleReport Command 2011 to 2015.xlsx
NPS MVCOccVehicleReport Command 2016 to 4-2018.xlsx
NPS MVCOccVehicleReport Command 4-2018 to 6-2021.xlsx

In [6]:
imars_crash_1 = pd.read_excel("./data/IMARS/NPS GOccIvPA Command Address 2011-2015.xlsx", sheet_name = "Batch1-Result1")

In [7]:
imars_crash_1 = pd.read_excel("./data/IMARS/NPS GOccIvPA Command Address 2011-2015.xlsx", sheet_name = "Batch1-Result1")
imars_crash_2 = pd.read_excel("./data/IMARS/NPS GOccIvPA Command Address 2016 to 4-2018.xlsx", sheet_name = "Batch1-Result1")
imars_crash_3 = pd.read_excel("./data/IMARS/NPS GOccIvPA Command Address 4-2018 to 6-2021.xlsx", sheet_name = "Batch1-Result1")

imars_passenger_1 = pd.read_excel("./data/IMARS/NPS MVCOccGPersonReport Command 2011 to 2015.xlsx", sheet_name = "Batch1-Result1")
imars_passenger_2 = pd.read_excel("./data/IMARS/NPS MVCOccGPersonReport Command 2016 to 4-2018.xlsx", sheet_name = "Batch1-Result1")
imars_passenger_3 = pd.read_excel("./data/IMARS/NPS MVCOccGPersonReport Command 4-2018 to 6-2021.xlsx", sheet_name = "Batch1-Result1")

imars_vehicle_1 = pd.read_excel("./data/IMARS/NPS MVCOccVehicleReport Command 2011 to 2015.xlsx", sheet_name = "Batch1-Result1")
imars_vehicle_2 = pd.read_excel("./data/IMARS/NPS MVCOccVehicleReport Command 2016 to 4-2018.xlsx", sheet_name = "Batch1-Result1")
imars_vehicle_3 = pd.read_excel("./data/IMARS/NPS MVCOccVehicleReport Command 4-2018 to 6-2021.xlsx", sheet_name = "Batch1-Result1")

imars_crash_details_1 = pd.read_excel("./data/IMARS/NPS MVCOccReportCommand_Classification 2011-2015.xlsx", sheet_name = "Batch1-Result1")
imars_crash_details_2 = pd.read_excel("./data/IMARS/NPS MVCOccReportCommand_Classification 2016 to 4-2018.xlsx", sheet_name = "Batch1-Result1")
imars_crash_details_3 = pd.read_excel("./data/IMARS/NPS MVCOccReportCommand_Classification 4-2018 to 6-2021.xlsx", sheet_name = "Batch1-Result1")

In [8]:
imars_crash = pd.concat([imars_crash_1, imars_crash_2, imars_crash_3])
imars_passenger = pd.concat([imars_passenger_1, imars_passenger_2, imars_passenger_3])
imars_vehicle = pd.concat([imars_vehicle_1, imars_vehicle_2, imars_vehicle_3])
imars_crash_details = pd.concat([imars_crash_details_1, imars_crash_details_2, imars_crash_details_3])

In [9]:
imars_crash.shape, imars_crash_1.shape, imars_crash_2.shape, imars_crash_3.shape

((12883, 32), (442, 32), (4454, 32), (7987, 32))

In [10]:
imars_passenger.shape, imars_passenger_1.shape, imars_passenger_2.shape, imars_passenger_3.shape

((19047, 28), (499, 28), (6782, 28), (11766, 28))

In [11]:
imars_vehicle.shape, imars_vehicle_1.shape, imars_vehicle_2.shape,imars_vehicle_3.shape

((16109, 51), (493, 51), (5529, 51), (10087, 51))

In [12]:
imars_crash_details.shape, imars_crash_details_1.shape, imars_crash_details_2.shape, imars_crash_details_3.shape

((11901, 24), (491, 24), (3907, 24), (7503, 24))

In [13]:
imars_crash.head()

,IMARS_Record_No,Crash_Date_Time,Linked_Address_Classification,City_Town_Park_Location,State,County,Direction,Linked_Street_Number,Linked_Common_Name,Street_Type,...,Latitude,Longitude,Region,State_Zone,Park,Site,Place,Point,Road_Type_Classification,Linked_Address
0,NP12000378,20120121 00:00:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Highway/road/alley (includes street),NaN
1,NP12000078,20120106 14:30:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NP12000935,20120215 10:15:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Highway/road/alley (includes street),NaN
3,NP12001003,20120218 10:50:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NP12000911,20120208 00:00:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Parking lot/garage,NaN

In [14]:
imars_passenger.Injury_Severity.value_counts()

01. No injury                    8398
99. Unknown                      1044
02. Possible injury               870
03. Non-incapacitating injury     724
04. Incapacitating injury         364
05. Fatal                          90
Name: Injury_Severity, dtype: int64

In [15]:
imars_passenger.columns

Index(['IMARS_Record_No', 'Crash_Date_Time', 'Driver_Action',
       'Driver_Condition', 'Driver_Distraction', 'Suspect_Alcohol',
       'Alcohol_Test', 'Alcohol_Test_Result_1', 'Alcohol_Test_Result_2',
       'Suspect_Drugs', 'Drug_Test', 'Violations_Issued', 'Seat_Position',
       'Injury_Severity', 'Air_Bag_Deployed', 'Ejection',
       'Injury_Transported_By', 'Safety_Equipment_Used',
       'Vehicle_number_striking_non_motorist', 'Injured_transported_by',
       'Non_motorist_safety_equipment',
       'Non_motorist_action_circumstance_prior_to_crash',
       'Non_motorist_action_circumstance_at_time_of_crash',
       'Non_motorist_condition_at_time_of_crash', 'Non_motorist_distraction',
       'Non_motorist_location_at_time_of_crash', 'Pedestrian_Type',
       'Pedestrian_Type_Detail'],
      dtype='object')

In [16]:
imars_crash.columns

Index(['IMARS_Record_No', 'Crash_Date_Time', 'Linked_Address_Classification',
       'City_Town_Park_Location', 'State', 'County', 'Direction',
       'Linked_Street_Number', 'Linked_Common_Name', 'Street_Type',
       'Direction.1', 'NEAR_Distance_to_MI', 'NEAR_Direction_To',
       'NEAR_Direction', 'NEAR_route_street_road_name', 'NEAR_Road_Type',
       'NEAR_Direction.1', 'AT_Intersection_route_street_road_DIRECTION',
       'At_Intersecting_route_street_road_name', 'AT_Road_Type',
       'AT_Direction', 'Mile_Marker', 'Latitude', 'Longitude', 'Region',
       'State_Zone', 'Park', 'Site', 'Place', 'Point',
       'Road_Type_Classification', 'Linked_Address'],
      dtype='object')

In [17]:
imars_crash_details.columns

Index(['IMARS_Record_No', 'Crash_Date_Time', 'Number_of_Vehicles_Involved',
       'Injury_or_Fatal_Crash', 'Investigated_at_Scene', 'Hit_and_Run',
       'Non_Motor_Vehicl_Property_Damage', 'Amount_of_Property_Damage',
       'First_Harmful_Event_Type', 'First_Harmful_Event',
       'Location_of_First_Harmful_Event', 'Weather', 'Roadway_Condition',
       'Lighting', 'School_Bus_related', 'AS_Road_Circumstance',
       'Environmental_Contributing_Circumstances', 'Work_Zone_Related',
       'Work_Zone_Workers_Present', 'Work_Zone_Location',
       'Law_Enforcement_Present_at_Work_Zone', 'Relation_to_Junction',
       'Type_of_Intersection', 'Manner_of_Collision'],
      dtype='object')

In [18]:
imars_vehicle.columns

Index(['IMARS_Record_No', 'Crash_Date_Time', 'Vehicle_Number',
       'Number_of_Occupants', 'Vehicle_Towed', 'Insurance_verified',
       'Initial_Impact_Point', 'Most_Damaged_Area', 'Extent_of_Damage',
       'Direction_of_Travel_Prior_to_Crash', 'Posted_Speed',
       'First_Event_Type', 'First_Event', 'Second_Event_Type', 'Second_Event',
       'Third_Event_Type', 'Third_Event', 'Fourth_Event_Type', 'Fourth_Event',
       'Motor_Vehicle_Unit_Type', 'Vehicle_Owner', 'Vehicle_Type',
       'Non_Commercial_Trailer_Style', 'Emergency_Vehicle_Use',
       'Emergency_Equipment_Activated', 'Special_Function_of_MV_in_Transport',
       'Motor_Vehicle_Contributing_Circumstance',
       'Vehicle_Maneuver_Action_Prior_to_Crash', 'Road_Surface', 'Grade',
       'Roadway_Alignment', 'Total_Number_of_Lanes', 'Traffic_Control',
       'Traffic_Control_Working_Properly', 'Roadway_Description',
       'Commercial_Non_Commercial', 'Number_of_Axles', 'Gross_Vehicle_Weight',
       'Combination_GVW', 'Commercial_Cargo_Body_Type', 'Commercial_Cargo',
       'Commercial_MV_Configuration', 'Identification_Number_Type',
       'Hazmat_1_Class', 'Hazmat_1_ID', 'Hazmat_2_Class', 'Hazmat_2_ID',
       'Hazmat_3_Class', 'Hazmat_3_ID', 'Hazmat_4_Class', 'Hazmat_4_ID'],
      dtype='object')

## Add Parks to Crash Details Dataset

**Note:** IMARS does not have park units with each crash, so these will have to be added using the Latitude and Longitude fields in the imars_crash dataset.

In [19]:
imars_crash.shape

(12883, 32)

In [20]:
imars_crash.dropna(subset=['Park']).shape

(5419, 32)

In [21]:
imars_crash['Region'].value_counts()

PWR    1763
IMR    1554
SER    1478
NER     369
MWR     178
AKR      74
NCR      18
Name: Region, dtype: int64

In [22]:
imars_crash.dropna(subset=['Park'])['Region'].value_counts()

PWR    1763
IMR    1539
SER    1478
NER     369
MWR     178
AKR      74
NCR      18
Name: Region, dtype: int64

In [23]:
imars_crash_parks = imars_crash.dropna(subset=['Park'])
imars_crash_parks.shape

(5419, 32)

In [24]:
imars_crash.loc[imars_crash['Park'].isnull()==False].shape

(5419, 32)

In [25]:
imars_crash.loc[imars_crash['Park'].isnull()==True].shape

(7464, 32)

In [26]:
imars_crash_coords = imars_crash.loc[imars_crash['Park'].isnull()==True].dropna(subset=['Latitude','Longitude'])
imars_crash_coords.shape

(3261, 32)

In [27]:
3261+5419

8680

In [28]:
imars_crash_coords = imars_crash.loc[imars_crash['Park'].isnull()==True].dropna(subset=['Latitude','Longitude'])
imars_crash_coords_geo=gpd.GeoDataFrame(imars_crash_coords, geometry=gpd.points_from_xy(imars_crash_coords.Longitude, 
                                                                             imars_crash_coords.Latitude))

In [29]:
filename = "./shapefiles/NPS_-_Land_Resources_Division_Boundary_and_Tract_Data_Service.geojson"
file = open(filename)
parks = gpd.read_file(file)

In [30]:
imars_crash_coords_geo.crs = "EPSG:4326"
parks.crs = "EPSG:4326"

In [31]:
parks['geometry']=parks['geometry'].buffer(0.2)

imars_crash_coords_geo_withparknames=gpd.sjoin(imars_crash_coords_geo,parks,how="left", op='intersects')
imars_crash_coords_geo_withparknames.head()

C:\Users\Eric.Englin\AppData\Local\Temp\ipykernel_11588\1885449436.py:1: UserWarning: Geometry is in a geographic CRS. Results from 'buffer' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  parks['geometry']=parks['geometry'].buffer(0.2)
C:\Users\Eric.Englin\Anaconda3\envs\geo_env\lib\site-packages\IPython\core\interactiveshell.py:3337: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

,IMARS_Record_No,Crash_Date_Time,Linked_Address_Classification,City_Town_Park_Location,State,County,Direction,Linked_Street_Number,Linked_Common_Name,Street_Type,...,CREATED_BY,METADATA,PARKNAME,CreationDate,Creator,EditDate,Editor,GlobalID,Shape__Area,Shape__Length
410,NP14039836,20140513 13:30:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
412,NP14049772,20140607 14:42:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,NP14060606,20140625 20:40:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Lands,Preliminary data. Contact the Land Resources P...,Olympic,2020-01-09T22:16:03+00:00,SCarlton@nps.gov_nps,2020-01-09T22:16:03+00:00,SCarlton@nps.gov_nps,d568927b-56f4-4f49-a52a-b8ab9f7676a3,8.203591e+09,1.158605e+06
5,NP16029926,20160326 20:00:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Lands,https://irma.nps.gov/DataStore/Reference/Profi...,Blue Ridge Parkway,2022-01-06T10:41:13+00:00,WASO,2022-01-06T10:41:13+00:00,WASO,a8ef8bcf-aaa2-4623-a8f6-1d93fe31f945,6.422579e+08,2.287707e+06
101,NP16041155,20160425 15:00:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Lands,https://irma.nps.gov/DataStore/Reference/Profi...,Grand Canyon,2022-01-06T10:42:52+00:00,WASO,2022-01-06T10:42:52+00:00,WASO,16feb031-8263-422e-8bdc-deb1a65f6153,7.487848e+09,2.135274e+06

In [32]:
imars_crash_coords_geo_withparknames.shape

(5137, 53)

In [33]:
imars_crash_coords_geo_withparknames2  = imars_crash_coords_geo_withparknames.drop_duplicates(subset=['IMARS_Record_No'])

In [34]:
imars_crash_coords_geo_withparknames2.shape

(3102, 53)

In [35]:
imars_crash_coords_geo_withparknames2.REGION.value_counts()

SE    1031
IM     507
PW     460
NE     285
MW      86
NC      52
AK       9
Name: REGION, dtype: int64

In [36]:
imars_crash_withparknames = pd.DataFrame(imars_crash_coords_geo_withparknames2.drop(columns='geometry'))
imars_crash_withparknames['Park']= imars_crash_withparknames['UNIT_CODE']

In [37]:
imars_crash_withparknames.shape

(3102, 52)

In [38]:
imars_crash_withparknames2 = imars_crash_withparknames[list(imars_crash_parks.columns)]
imars_crash_withparknames2.shape

(3102, 32)

In [39]:
imars_crash_expanded = pd.concat([imars_crash_parks,imars_crash_withparknames2])
imars_crash_expanded  = imars_crash_expanded.drop_duplicates(subset=['IMARS_Record_No'])
imars_crash_expanded.shape

(7811, 32)

In [52]:
imars_crash_expanded.Region.value_counts()

PWR    1660
SER    1420
IMR    1354
NER     354
MWR     165
AKR      62
NCR      18
Name: Region, dtype: int64

In [50]:
imars_crash_expanded.columns

Index(['IMARS_Record_No', 'Crash_Date_Time', 'Linked_Address_Classification',
       'City_Town_Park_Location', 'State', 'County', 'Direction',
       'Linked_Street_Number', 'Linked_Common_Name', 'Street_Type',
       'Direction.1', 'NEAR_Distance_to_MI', 'NEAR_Direction_To',
       'NEAR_Direction', 'NEAR_route_street_road_name', 'NEAR_Road_Type',
       'NEAR_Direction.1', 'AT_Intersection_route_street_road_DIRECTION',
       'At_Intersecting_route_street_road_name', 'AT_Road_Type',
       'AT_Direction', 'Mile_Marker', 'Latitude', 'Longitude', 'Region',
       'State_Zone', 'Park', 'Site', 'Place', 'Point',
       'Road_Type_Classification', 'Linked_Address', 'CRASH_DATE',
       'CRASH_TIME', 'CRASH_YEAR'],
      dtype='object')

In [53]:
imars_crash_expanded.loc[imars_crash_expanded['Region']=="NCR"].Park.value_counts()

MANA    13
PRWI     4
CATO     1
Name: Park, dtype: int64

## Filter for COLM

In [41]:
imars_crash_expanded.head()

,IMARS_Record_No,Crash_Date_Time,Linked_Address_Classification,City_Town_Park_Location,State,County,Direction,Linked_Street_Number,Linked_Common_Name,Street_Type,...,Latitude,Longitude,Region,State_Zone,Park,Site,Place,Point,Road_Type_Classification,Linked_Address
234,NP13031262,20130615 14:00:00:000,Dispatch address,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,MWR,AR,BUFF,NaN,NaN,NaN,Highway/road/alley (includes street),NEAR THE OLD SIGN BUFFALO POINT
349,NP13054509,20130803 10:56:00:000,Dispatch address,NaN,SD,NaN,NaN,NaN,PPI-ENTRANCE/EXIT,NaN,...,NaN,NaN,MWR,SD,MORU,NaN,NaN,NaN,Highway/road/alley (includes street),PPI-ENTRANCE/EXIT
364,NP13071209,20130905 12:03:00:000,Dispatch address,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NER,VA,SHEN,NaN,NaN,NaN,Convenience store,BM WAYSIDE
375,NP13082489,20131006 09:10:00:000,Dispatch address,NaN,VA,NaN,NaN,NaN,MP97,NaN,...,NaN,NaN,NER,VA,SHEN,NaN,NaN,NaN,Highway/road/alley (includes street),MP97
376,NP13082534,20131006 11:42:00:000,Dispatch address,NaN,VA,NaN,NaN,NaN,MP102,NaN,...,NaN,NaN,NER,VA,SHEN,NaN,NaN,NaN,Highway/road/alley (includes street),MP102

In [43]:
imars_crash_expanded['Crash_Date_Time']=pd.to_datetime(imars_crash_expanded['Crash_Date_Time'], 
                                                   format='%Y%m%d %H:%M:%S:%f')

imars_crash_expanded['CRASH_DATE'] = imars_crash_expanded['Crash_Date_Time'].dt.strftime('%m/%d/%Y')
imars_crash_expanded['CRASH_TIME'] = imars_crash_expanded['Crash_Date_Time'].dt.strftime('%H%M')
imars_crash_expanded['CRASH_YEAR'] = imars_crash_expanded['Crash_Date_Time'].dt.strftime('%Y')

In [44]:
imars_crash_expanded_gwmp = imars_crash_expanded.loc[imars_crash_expanded['Park']=='GWMP']

In [45]:
imars_crash_expanded_gwmp.head()

Empty DataFrame
Columns: [IMARS_Record_No, Crash_Date_Time, Linked_Address_Classification, City_Town_Park_Location, State, County, Direction, Linked_Street_Number, Linked_Common_Name, Street_Type, Direction.1, NEAR_Distance_to_MI, NEAR_Direction_To, NEAR_Direction, NEAR_route_street_road_name, NEAR_Road_Type, NEAR_Direction.1, AT_Intersection_route_street_road_DIRECTION, At_Intersecting_route_street_road_name, AT_Road_Type, AT_Direction, Mile_Marker, Latitude, Longitude, Region, State_Zone, Park, Site, Place, Point, Road_Type_Classification, Linked_Address, CRASH_DATE, CRASH_TIME, CRASH_YEAR]
Index: []

[0 rows x 35 columns]

In [91]:

imars_crash_expanded_colm.to_csv("./IMARS_COLM_crash.csv",index=False)

In [ ]:
imars_crash = pd.concat([imars_crash_1, imars_crash_2, imars_crash_3])
imars_passenger = pd.concat([imars_passenger_1, imars_passenger_2, imars_passenger_3])
imars_vehicle = pd.concat([imars_vehicle_1, imars_vehicle_2, imars_vehicle_3])
 = pd.concat([imars_crash_details_1, imars_crash_details_2, imars_crash_details_3])

In [83]:
imars_crash_expanded_colm.columns

Index(['IMARS_Record_No', 'Crash_Date_Time', 'Linked_Address_Classification',
       'City_Town_Park_Location', 'State', 'County', 'Direction',
       'Linked_Street_Number', 'Linked_Common_Name', 'Street_Type',
       'Direction.1', 'NEAR_Distance_to_MI', 'NEAR_Direction_To',
       'NEAR_Direction', 'NEAR_route_street_road_name', 'NEAR_Road_Type',
       'NEAR_Direction.1', 'AT_Intersection_route_street_road_DIRECTION',
       'At_Intersecting_route_street_road_name', 'AT_Road_Type',
       'AT_Direction', 'Mile_Marker', 'Latitude', 'Longitude', 'Region',
       'State_Zone', 'Park', 'Site', 'Place', 'Point',
       'Road_Type_Classification', 'Linked_Address', 'CRASH_DATE',
       'CRASH_TIME', 'CRASH_YEAR'],
      dtype='object')

In [89]:
imars_passenger_merged = imars_passenger.merge(imars_crash_expanded_colm[['IMARS_Record_No','Latitude', 'Longitude','Park',
                                                                         'CRASH_DATE','CRASH_TIME', 'CRASH_YEAR']] , 
                                               how='left', on='IMARS_Record_No')

imars_passenger_colm = imars_passenger_merged.loc[imars_passenger_merged['Park']=='COLM']

In [90]:
imars_passenger_colm.to_csv("./IMARS_COLM_passenger.csv",index=False)

In [92]:
imars_vehicle_merged = imars_vehicle.merge(imars_crash_expanded_colm[['IMARS_Record_No','Latitude', 'Longitude','Park',
                                                                         'CRASH_DATE','CRASH_TIME', 'CRASH_YEAR']] , 
                                               how='left', on='IMARS_Record_No')

imars_vehicle_colm = imars_vehicle_merged.loc[imars_vehicle_merged['Park']=='COLM']
imars_vehicle_colm

,IMARS_Record_No,Crash_Date_Time,Vehicle_Number,Number_of_Occupants,Vehicle_Towed,Insurance_verified,Initial_Impact_Point,Most_Damaged_Area,Extent_of_Damage,Direction_of_Travel_Prior_to_Crash,...,Hazmat_3_Class,Hazmat_3_ID,Hazmat_4_Class,Hazmat_4_ID,Latitude,Longitude,Park,CRASH_DATE,CRASH_TIME,CRASH_YEAR
1368,NP16167348,20160912 01:30:00:000,1.0,1.0,Yes,Yes,12. Clock point 12,12. Clock point 12,04. Disabling,02. Eastbound,...,11. Not applicable,NaN,11. Not applicable,NaN,39.076672,-108.729394,COLM,09/12/2016,0130,2016
9216,NP19025391,20190225 13:30:00:000,1.0,1.0,Yes,No,14. Undercarriage,99. Unknown,99. Unknown,02. Eastbound,...,NaN,NaN,NaN,NaN,39.026378,-108.660106,COLM,02/25/2019,1330,2019
9342,NP19033513,20190404 10:00:00:000,1.0,1.0,No,Yes,11. Clock point 11,14. Undercarriage,02. Functional,01. Northbound,...,NaN,NaN,NaN,NaN,39.026975,-108.656694,COLM,04/04/2019,1000,2019
9354,NP19033952,20190405 17:30:00:000,1.0,2.0,Yes,Yes,01. Clock point 1,01. Clock point 1,04. Disabling,04. Westbound,...,NaN,NaN,NaN,NaN,39.116300,-108.736800,COLM,04/05/2019,1730,2019
9486,NP19040134,20190414 13:00:00:000,1.0,3.0,Yes,Yes,06. Clock point 6,06. Clock point 6,04. Disabling,04. Westbound,...,NaN,NaN,NaN,NaN,39.031990,-108.630889,COLM,04/14/2019,1300,2019
9487,NP19040134,20190414 13:00:00:000,2.0,1.0,No,Yes,12. Clock point 12,12. Clock point 12,03. Minor,04. Westbound,...,NaN,NaN,NaN,NaN,39.031990,-108.630889,COLM,04/14/2019,1300,2019
10105,NP19082075,20190618 11:49:00:000,1.0,2.0,No,Yes,12. Clock point 12,NaN,NaN,04. Westbound,...,NaN,NaN,NaN,NaN,39.035244,-108.630381,COLM,06/18/2019,1149,2019
10106,NP19082075,20190618 11:49:00:000,2.0,1.0,No,Yes,06. Clock point 6,06. Clock point 6,NaN,04. Westbound,...,NaN,NaN,NaN,NaN,39.035244,-108.630381,COLM,06/18/2019,1149,2019
10624,NP19116095,20190726 09:30:00:000,1.0,1.0,No,Yes,01. Clock point 1,01. Clock point 1,02. Functional,02. Eastbound,...,NaN,NaN,NaN,NaN,39.031577,-108.646821,COLM,07/26/2019,0930,2019
11090,NP19150503,20190904 12:22:00:000,1.0,2.0,No,Unknown,07. Clock point 7,07. Clock point 7,NaN,05. Not on roadway,...,NaN,NaN,NaN,NaN,39.034557,-108.646236,COLM,09/04/2019,1222,2019
11555,NP19175696,20191011 09:35:00:000,1.0,2.0,Yes,Yes,12. Clock point 12,12. Clock point 12,04. Disabling,01. Northbound,...,NaN,NaN,NaN,NaN,39.031903,-108.630942,COLM,10/11/2019,0935,2019
11556,NP19175696,20191011 09:35:00:000,2.0,1.0,No,Yes,06. Clock point 6,06. Clock point 6,02. Functional,01. Northbound,...,NaN,NaN,NaN,NaN,39.031903,-108.630942,COLM,10/11/2019,0935,2019
12204,NP20004395,20200109 06:30:00:000,1.0,1.0,Yes,Yes,01. Clock point 1,01. Clock point 1,04. Disabling,02. Eastbound,...,NaN,NaN,NaN,NaN,39.032611,-108.647278,COLM,01/09/2020,0630,2020
12543,NP20028526,20200315 02:00:00:000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,39.028056,-108.639722,COLM,03/15/2020,0200,2020
12596,NP20034288,20200402 02:30:00:000,1.0,5.0,Yes,Yes,11. Clock point 11,11. Clock point 11,NaN,02. Eastbound,...,NaN,NaN,NaN,NaN,39.033376,-108.645965,COLM,04/02/2020,0230,2020
12734,NP20051235,20200523 02:12:00:000,1.0,2.0,No,No,01. Clock point 1,01. Clock point 1,02. Functional,04. Westbound,...,NaN,NaN,NaN,NaN,39.026153,-108.657186,COLM,05/23/2020,0212,2020
12771,NP20050722,20200526 12:45:00:000,1.0,1.0,No,Unknown,NaN,NaN,03. Minor,02. Eastbound,...,NaN,NaN,NaN,NaN,39.030834,-108.645706,COLM,05/26/2020,1245,2020
13502,NP20101203,20200805 06:00:00:000,1.0,1.0,Yes,No,12. Clock point 12,12. Clock point 12,04. Disabling,04. Westbound,...,NaN,NaN,NaN,NaN,39.030531,-108.654446,COLM,08/05/2020,0600,2020
14066,NP20138424,20200926 03:30:00:000,1.0,1.0,No,No,NaN,NaN,NaN,02. Eastbound,...,NaN,NaN,NaN,NaN,39.026111,-108.640556,COLM,09/26/2020,0330,2020
14323,NP20151463,20201011 04:30:00:000,1.0,2.0,Yes,Yes,01. Clock point 1,13. Top/roof,04. Disabling,02. Eastbound,...,NaN,NaN,NaN,NaN,39.045833,-108.620000,COLM,10/11/2020,0430,2020
14867,NP21006969,20210123 23:15:00:000,1.0,1.0,Yes,Yes,01. Clock point 1,13. Top/roof,04. Disabling,04. Westbound,...,NaN,NaN,NaN,NaN,39.028150,-108.635820,COLM,01/23/2021,2315,2021
15366,NP21036615,20210421 12:00:00:000,1.0,2.0,No,Yes,06. Clock point 6,06. Clock point 6,03. Minor,05. Not on roadway,...,NaN,NaN,NaN,NaN,39.104700,-108.732800,COLM,04/21/2021,1200,2021
15433,NP21042088,20210417 14:30:00:000,1.0,1.0,No,Yes,07. Clock point 7,07. Clock point 7,NaN,03. Southbound,...,NaN,NaN,NaN,NaN,39.033065,-108.633326,COLM,04/17/2021,1430,2021
15434,NP21042088,20210417 14:30:00:000,2.0,0.0,No,Yes,03. Clock point 3,NaN,03. Minor,05. Not on roadway,...,NaN,NaN,NaN,NaN,39.033065,-108.633326,COLM,04/17/2021,1430,2021

In [93]:
imars_vehicle_colm.to_csv("./IMARS_COLM_vehicle.csv",index=False)

In [95]:
imars_crash_details_merged = imars_crash_details.merge(imars_crash_expanded_colm[['IMARS_Record_No','Latitude', 'Longitude','Park',
                                                                         'CRASH_DATE','CRASH_TIME', 'CRASH_YEAR']] , 
                                               how='left', on='IMARS_Record_No')

imars_crash_details_colm = imars_crash_details_merged.loc[imars_crash_details_merged['Park']=='COLM']
imars_crash_details_colm

,IMARS_Record_No,Crash_Date_Time,Number_of_Vehicles_Involved,Injury_or_Fatal_Crash,Investigated_at_Scene,Hit_and_Run,Non_Motor_Vehicl_Property_Damage,Amount_of_Property_Damage,First_Harmful_Event_Type,First_Harmful_Event,...,Law_Enforcement_Present_at_Work_Zone,Relation_to_Junction,Type_of_Intersection,Manner_of_Collision,Latitude,Longitude,Park,CRASH_DATE,CRASH_TIME,CRASH_YEAR
1723,NP16167348,20160912 01:30:00:000,1.0,NaN,Yes,No,Yes,Unknown,Collision with fixed object,"60. Rock, boulder, rock slide",...,04. Not applicable,01. Non-junction,01. Not an intersection,08. Other,39.076672,-108.729394,COLM,09/12/2016,0130,2016
6766,NP19025391,20190225 13:30:00:000,1.0,02. No,NaN,NaN,NaN,NaN,Collision with fixed object,52. Tree/shrub,...,01. No,01. Non-junction,01. Not an intersection,08. Other,39.026378,-108.660106,COLM,02/25/2019,1330,2019
6860,NP19033513,20190404 10:00:00:000,1.0,02. No,Yes,No,No,Under $1000,Non-collision,07. Ran off the road right,...,01. No,01. Non-junction,01. Not an intersection,01. Front to rear,39.026975,-108.656694,COLM,04/04/2019,1000,2019
6866,NP19033952,20190405 17:30:00:000,1.0,02. No,Yes,No,No,Not applicable,Collision with fixed object,66. Other fixed object,...,01. No,01. Non-junction,01. Not an intersection,08. Other,39.116300,-108.736800,COLM,04/05/2019,1730,2019
6958,NP19040134,20190414 13:00:00:000,2.0,02. No,Yes,No,No,NaN,"Collision with person, MV or non-fixed object",21. Motor vehicle in transport,...,01. No,02. Intersection,03. T intersection,01. Front to rear,39.031990,-108.630889,COLM,04/14/2019,1300,2019
7433,NP19082075,20190618 11:49:00:000,2.0,02. No,Yes,No,NaN,NaN,"Collision with person, MV or non-fixed object",21. Motor vehicle in transport,...,NaN,NaN,NaN,01. Front to rear,39.035244,-108.630381,COLM,06/18/2019,1149,2019
7801,NP19116095,20190726 09:30:00:000,1.0,02. No,No,No,No,Under $1000,Collision with animals,34. Sheep/goats,...,01. No,01. Non-junction,01. Not an intersection,03. Angle,39.031577,-108.646821,COLM,07/26/2019,0930,2019
8149,NP19150503,20190904 12:22:00:000,1.0,02. No,No,No,No,Not applicable,Collision with fixed object,"60. Rock, boulder, rock slide",...,01. No,01. Non-junction,01. Not an intersection,08. Other,39.034557,-108.646236,COLM,09/04/2019,1222,2019
8485,NP19175696,20191011 09:35:00:000,2.0,02. No,Yes,No,No,Under $1000,"Collision with person, MV or non-fixed object",25. Other non-fixed object,...,01. No,"13. Other non-interchange (i.e. bike, snowmobi...",08. Other,01. Front to rear,39.031903,-108.630942,COLM,10/11/2019,0935,2019
8979,NP20004395,20200109 06:30:00:000,1.0,02. No,Yes,No,NaN,NaN,Collision with fixed object,50. Wall,...,01. No,NaN,NaN,03. Angle,39.032611,-108.647278,COLM,01/09/2020,0630,2020
9227,NP20028526,20200315 02:00:00:000,1.0,02. No,NaN,NaN,NaN,NaN,Collision with fixed object,52. Tree/shrub,...,NaN,NaN,NaN,"04. Sideswipe, same direction",39.028056,-108.639722,COLM,03/15/2020,0200,2020
9271,NP20034288,20200402 02:30:00:000,1.0,02. No,NaN,NaN,NaN,NaN,Collision with fixed object,49. Guardrail/concrete traffic barrier,...,NaN,NaN,NaN,"04. Sideswipe, same direction",39.033376,-108.645965,COLM,04/02/2020,0230,2020
9381,NP20051235,20200523 02:12:00:000,1.0,02. No,No,NaN,NaN,NaN,Collision with fixed object,52. Tree/shrub,...,NaN,NaN,NaN,08. Other,39.026153,-108.657186,COLM,05/23/2020,0212,2020
9409,NP20050722,20200526 12:45:00:000,1.0,01. Yes,Yes,No,No,NaN,Collision with fixed object,66. Other fixed object,...,01. No,01. Non-junction,01. Not an intersection,08. Other,39.030834,-108.645706,COLM,05/26/2020,1245,2020
9939,NP20101203,20200805 06:00:00:000,1.0,02. No,Yes,No,Yes,Unknown,Collision with fixed object,49. Guardrail/concrete traffic barrier,...,01. No,01. Non-junction,01. Not an intersection,02. Front to front,39.030531,-108.654446,COLM,08/05/2020,0600,2020
10367,NP20138424,20200926 03:30:00:000,1.0,02. No,Yes,No,NaN,NaN,Collision with fixed object,"60. Rock, boulder, rock slide",...,NaN,NaN,NaN,03. Angle,39.026111,-108.640556,COLM,09/26/2020,0330,2020
10562,NP20151463,20201011 04:30:00:000,1.0,01. Yes,Yes,No,Yes,Under $1000,Collision with fixed object,"60. Rock, boulder, rock slide",...,01. No,01. Non-junction,01. Not an intersection,08. Other,39.045833,-108.620000,COLM,10/11/2020,0430,2020
11003,NP21006969,20210123 23:15:00:000,1.0,01. Yes,Yes,No,No,NaN,Collision with fixed object,"60. Rock, boulder, rock slide",...,01. No,01. Non-junction,01. Not an intersection,"04. Sideswipe, same direction",39.028150,-108.635820,COLM,01/23/2021,2315,2021
11357,NP21036615,20210421 12:00:00:000,2.0,02. No,No,Yes,No,Unknown,"Collision with person, MV or non-fixed object",22. Parked motor vehicle,...,01. No,01. Non-junction,01. Not an intersection,99. Unknown,39.104700,-108.732800,COLM,04/21/2021,1200,2021
11412,NP21042088,20210417 14:30:00:000,2.0,02. No,NaN,NaN,NaN,NaN,"Collision with person, MV or non-fixed object",21. Motor vehicle in transport,...,NaN,NaN,NaN,06. Rear to side,39.033065,-108.633326,COLM,04/17/2021,1430,2021

In [96]:
imars_crash_details_colm.to_csv("./IMARS_COLM_crash_details.csv",index=False)

In [97]:
imars_crash_details_colm.shape, imars_passenger_colm.shape, imars_vehicle_colm.shape, imars_crash_expanded_colm.shape

((20, 30), (28, 34), (24, 57), (20, 35))

## Step 2: Filter for Necessary Fields, Group by IMARS_RECORD_NO

#### Creating New Columns for Injury Severity

- Requires passenger dataset

In [40]:
imars_passenger.columns

Index(['IMARS_Record_No', 'Crash_Date_Time', 'Driver_Action',
       'Driver_Condition', 'Driver_Distraction', 'Suspect_Alcohol',
       'Alcohol_Test', 'Alcohol_Test_Result_1', 'Alcohol_Test_Result_2',
       'Suspect_Drugs', 'Drug_Test', 'Violations_Issued', 'Seat_Position',
       'Injury_Severity', 'Air_Bag_Deployed', 'Ejection',
       'Injury_Transported_By', 'Safety_Equipment_Used',
       'Vehicle_number_striking_non_motorist', 'Injured_transported_by',
       'Non_motorist_safety_equipment',
       'Non_motorist_action_circumstance_prior_to_crash',
       'Non_motorist_action_circumstance_at_time_of_crash',
       'Non_motorist_condition_at_time_of_crash', 'Non_motorist_distraction',
       'Non_motorist_location_at_time_of_crash', 'Pedestrian_Type',
       'Pedestrian_Type_Detail', 'NUM_OCC', 'INCID_NO'],
      dtype='object')

In [41]:
imars_passenger['NUM_OCC'] = 1
imars_passenger['INCID_NO'] = imars_passenger['IMARS_Record_No']
imars_passenger['Crash_Date_Time_report'] = imars_passenger['Crash_Date_Time']

imars_passenger_slim = imars_passenger[[
    'INCID_NO', 'NUM_OCC', 'Crash_Date_Time_report','Injury_Severity'
]]

In [42]:
imars_passenger_slim.head()

     INCID_NO  NUM_OCC Crash_Date_Time_report Injury_Severity
0  NP12000078        1  20120106 14:30:00:000             NaN
1  NP12000378        1  20120121 00:00:00:000             NaN
2  NP12000550        1  20120131 13:51:00:000             NaN
3  NP12000911        1  20120208 00:00:00:000             NaN
4  NP12000935        1  20120215 10:15:00:000             NaN

In [43]:
imars_passenger_slim['No Injury']= np.where(imars_passenger_slim['Injury_Severity']=='01. No injury', 1,0)
imars_passenger_slim['Possible Injury']= np.where(imars_passenger_slim['Injury_Severity']=='02. Possible injury', 1,0)
imars_passenger_slim['Non-incapacitating Injury']= np.where(imars_passenger_slim['Injury_Severity']=='03. Non-incapacitating injury', 1,0)
imars_passenger_slim['Incapacitating Injury']= np.where(imars_passenger_slim['Injury_Severity']=='04. Incapacitating injury', 1,0)
imars_passenger_slim['Fatality']= np.where(imars_passenger_slim['Injury_Severity']=='05. Fatal', 1,0)
imars_passenger_slim['Unknown Injury']= np.where(imars_passenger_slim['Injury_Severity']=='99. Unknown', 1,0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [44]:
imars_passenger_slim.Fatality.sum()

90

In [45]:
imars_passenger_slim_agg = imars_passenger_slim.groupby(by=['INCID_NO']).sum()
#imars_slim_agg = imars_slim_agg.drop(columns = ['ACCLASS','DINJ', 'PINJ'])
imars_passenger_slim_agg = imars_passenger_slim_agg.reset_index()

In [46]:
imars_passenger_slim_agg.shape

(11076, 8)

In [47]:
imars_passenger_slim_agg.Fatality.sum()

90

#### Creating New Columns for Accident Class

In [48]:
imars_crash_details['INCID_NO'] = imars_crash_details['IMARS_Record_No']

imars_crash_details_slim = imars_crash_details[[
    'INCID_NO', 'First_Harmful_Event_Type','First_Harmful_Event'
]]

In [49]:
imars_crash_details_slim.First_Harmful_Event_Type.value_counts()

Collision with person, MV or non-fixed object    4611
Collision with fixed object                      3358
Non-collision                                    1639
Collision with animals                           1247
Unknown                                           406
Name: First_Harmful_Event_Type, dtype: int64

In [50]:
imars_crash_details_slim.loc[imars_crash_details_slim['First_Harmful_Event_Type']=="Collision with person, MV or non-fixed object"].First_Harmful_Event.value_counts()

21. Motor vehicle in transport                                           2843
22. Parked motor vehicle                                                 1281
25. Other non-fixed object                                                295
18. Bicycle                                                                57
17. Pedestrian                                                             52
24. Work zone/maintenance equipment                                        25
23. Struck by falling, shifting cargo or anything set in motion by MV      16
20. Railway vehicle                                                         2
99. Unknown                                                                 1
Name: First_Harmful_Event, dtype: int64

In [51]:
pd.options.mode.chained_assignment = None  # default='warn'

imars_crash_details_slim['Collision with Fixed Object']= np.where(imars_crash_details_slim['First_Harmful_Event_Type']=="Collision with fixed object", 1,0)
imars_crash_details_slim['Collision with Animal']= np.where(imars_crash_details_slim['First_Harmful_Event_Type']=="Collision with animals", 1,0)
imars_crash_details_slim['Non-Collision']= np.where(imars_crash_details_slim['First_Harmful_Event_Type']=="Non-collision", 1,0)
imars_crash_details_slim['Other Accident Class']= np.where(imars_crash_details_slim['First_Harmful_Event_Type']=="Unknown",1,0)


imars_crash_details_slim['Collision with Other Motor Vehicle']= np.where(imars_crash_details_slim['First_Harmful_Event']=='21. Motor vehicle in transport', 1,0)
imars_crash_details_slim['Collision with Pedestrian']= np.where(imars_crash_details_slim['First_Harmful_Event']=="17. Pedestrian", 1,0)
imars_crash_details_slim['Collision with Bicycle']= np.where(imars_crash_details_slim['First_Harmful_Event']=="18. Bicycle", 1,0)
imars_crash_details_slim['Collision with Parked Motor Vehicle']= np.where(imars_crash_details_slim['First_Harmful_Event']=="22. Parked motor vehicle", 1,0)
imars_crash_details_slim['Collision with Railway Train']= np.where(imars_crash_details_slim['First_Harmful_Event']=="20. Railway vehicle", 1,0)
imars_crash_details_slim['Collision with Other Object']= np.where(imars_crash_details_slim['First_Harmful_Event']=="25. Other non-fixed object", 1,0)
imars_crash_details_slim['Collision with Unknown']= np.where(imars_crash_details_slim['First_Harmful_Event'].isin(['23. Struck by falling, shifting cargo or anything set in motion by MV',
                                                                                              '24. Work zone/maintenance equipment']), 1,0)

In [52]:
imars_crash_details_slim['Non-Collision'].value_counts()

0    10262
1     1639
Name: Non-Collision, dtype: int64

In [53]:
imars_crash_details_slim_nodups = imars_crash_details_slim.drop_duplicates()
imars_passenger_slim_agg_nodups = imars_passenger_slim_agg.drop_duplicates()

In [54]:
imars_crash_clean = imars_crash_expanded[['IMARS_Record_No','Latitude', 'Longitude', 'Park','Crash_Date_Time']]
imars_crash_clean = imars_crash_clean.rename(columns={"IMARS_Record_No": "INCID_NO"})

imars_crash_clean = imars_crash_clean.drop_duplicates("INCID_NO")

In [55]:
imars_crash_details_slim_nodups.shape, imars_crash_clean.shape, imars_passenger_slim_agg_nodups.shape

((11131, 14), (7811, 5), (11076, 8))

In [56]:
imars_slim_agg=imars_crash_clean.merge(imars_passenger_slim_agg_nodups, how='left', on='INCID_NO')
imars_slim_agg=imars_slim_agg.merge(imars_crash_details_slim_nodups, how='left', on='INCID_NO')

In [57]:
imars_slim_agg.shape, imars_crash_details_slim_nodups.shape, imars_crash_clean.shape, imars_passenger_slim_agg_nodups.shape

((7842, 25), (11131, 14), (7811, 5), (11076, 8))

In [58]:
imars_slim_agg.Fatality.sum()

71

In [59]:
imars_slim_agg.head()

,INCID_NO,Latitude,Longitude,Park,Crash_Date_Time,NUM_OCC,No Injury,Possible Injury,Non-incapacitating Injury,Incapacitating Injury,...,Collision with Animal,Non-Collision,Other Accident Class,Collision with Other Motor Vehicle,Collision with Pedestrian,Collision with Bicycle,Collision with Parked Motor Vehicle,Collision with Railway Train,Collision with Other Object,Collision with Unknown
0,NP13031262,NaN,NaN,BUFF,20130615 14:00:00:000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NP13054509,NaN,NaN,MORU,20130803 10:56:00:000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,NP13071209,NaN,NaN,SHEN,20130905 12:03:00:000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,NP13082489,NaN,NaN,SHEN,20131006 09:10:00:000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,NP13082534,NaN,NaN,SHEN,20131006 11:42:00:000,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [60]:
imars_slim_agg.columns

Index(['INCID_NO', 'Latitude', 'Longitude', 'Park', 'Crash_Date_Time',
       'NUM_OCC', 'No Injury', 'Possible Injury', 'Non-incapacitating Injury',
       'Incapacitating Injury', 'Fatality', 'Unknown Injury',
       'First_Harmful_Event_Type', 'First_Harmful_Event',
       'Collision with Fixed Object', 'Collision with Animal', 'Non-Collision',
       'Other Accident Class', 'Collision with Other Motor Vehicle',
       'Collision with Pedestrian', 'Collision with Bicycle',
       'Collision with Parked Motor Vehicle', 'Collision with Railway Train',
       'Collision with Other Object', 'Collision with Unknown'],
      dtype='object')

In [61]:
imars_slim_agg = imars_slim_agg[['INCID_NO', 'NUM_OCC','Park', 'Non-Collision',
       'Collision with Other Motor Vehicle', 'Collision with Fixed Object',
       'Collision with Pedestrian', 'Collision with Bicycle',
       'Collision with Parked Motor Vehicle', 'Collision with Railway Train',
       'Collision with Animal', 'Collision with Other Object',
       'Collision with Unknown', 'Other Accident Class', 'No Injury',
       'Possible Injury', 'Non-incapacitating Injury', 'Incapacitating Injury',
       'Fatality', 'Unknown Injury', 'Latitude', 'Longitude', 'Crash_Date_Time']]

In [62]:
imars_slim_agg.head()

,INCID_NO,NUM_OCC,Park,Non-Collision,Collision with Other Motor Vehicle,Collision with Fixed Object,Collision with Pedestrian,Collision with Bicycle,Collision with Parked Motor Vehicle,Collision with Railway Train,...,Other Accident Class,No Injury,Possible Injury,Non-incapacitating Injury,Incapacitating Injury,Fatality,Unknown Injury,Latitude,Longitude,Crash_Date_Time
0,NP13031262,1,BUFF,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,20130615 14:00:00:000
1,NP13054509,1,MORU,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,20130803 10:56:00:000
2,NP13071209,1,SHEN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,20130905 12:03:00:000
3,NP13082489,1,SHEN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,20131006 09:10:00:000
4,NP13082534,1,SHEN,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,NaN,NaN,20131006 11:42:00:000

In [63]:
imars_slim_agg.Fatality.sum()

71

## COLM

In [67]:
imars_slim_agg.loc[imars_slim_agg['Park']=='COLM']

,INCID_NO,NUM_OCC,Park,Non-Collision,Collision with Other Motor Vehicle,Collision with Fixed Object,Collision with Pedestrian,Collision with Bicycle,Collision with Parked Motor Vehicle,Collision with Railway Train,...,Other Accident Class,No Injury,Possible Injury,Non-incapacitating Injury,Incapacitating Injury,Fatality,Unknown Injury,Latitude,Longitude,Crash_Date_Time
5083,NP16167348,1,COLM,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,39.076672,-108.729394,20160912 01:30:00:000
6121,NP19025391,1,COLM,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,39.026378,-108.660106,20190225 13:30:00:000
6172,NP19033513,1,COLM,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,39.026975,-108.656694,20190404 10:00:00:000
6177,NP19033952,1,COLM,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,39.116300,-108.736800,20190405 17:30:00:000
6219,NP19040134,2,COLM,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,39.031990,-108.630889,20190414 13:00:00:000
6427,NP19082075,2,COLM,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,39.035244,-108.630381,20190618 11:49:00:000
6583,NP19116095,1,COLM,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,39.031577,-108.646821,20190726 09:30:00:000
6730,NP19150503,2,COLM,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,39.034557,-108.646236,20190904 12:22:00:000
6867,NP19175696,4,COLM,0,0,0,0,0,0,0,...,0,3,0,0,0,0,0,39.031903,-108.630942,20191011 09:35:00:000
7068,NP20004395,1,COLM,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,39.032611,-108.647278,20200109 06:30:00:000
7166,NP20028526,1,COLM,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,39.028056,-108.639722,20200315 02:00:00:000
7182,NP20034288,1,COLM,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,39.033376,-108.645965,20200402 02:30:00:000
7224,NP20050722,1,COLM,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,39.030834,-108.645706,20200526 12:45:00:000
7228,NP20051235,2,COLM,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,39.026153,-108.657186,20200523 02:12:00:000
7386,NP20101203,1,COLM,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,39.030531,-108.654446,20200805 06:00:00:000
7513,NP20138424,1,COLM,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,39.026111,-108.640556,20200926 03:30:00:000
7562,NP20151463,2,COLM,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,39.045833,-108.620000,20201011 04:30:00:000
7656,NP21006969,1,COLM,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,39.028150,-108.635820,20210123 23:15:00:000
7745,NP21036615,1,COLM,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,39.104700,-108.732800,20210421 12:00:00:000
7760,NP21042088,1,COLM,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,39.033065,-108.633326,20210417 14:30:00:000

In [265]:
imars_slim_agg.to_csv("./crash_data_IMARS_clean.csv",index=False)